"""empty message

Revision ID: 51624a2b290e
Revises: 
Create Date: 2021-08-11 15:38:26.590145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51624a2b290e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('print_name', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('n_submit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_primary_key', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('Person', sa.Float(), nullable=False),
    sa.Column('Company', sa.Float(), nullable=False),
    sa.Column('City', sa.Float(), nullable=False),
    sa.Column('Compound', sa.Float(), nullable=False),
    sa.Column('Airport', sa.Float(), nullable=False),
    sa.Column('Overall', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_primary_key'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('users')
    # ### end Alembic commands ###
